/*
 * Created on 21 May 2016 ( Time 16:25:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package ht.bms.calendar.domain.repo;

import ht.bms.calendar.domain.BmsCalendar;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Optional;




/**
 * Spring JPA Repository for BmsCalendar
 * 
 * @author Telosys Tools Generator
 *
 */
public interface BmsCalendarRepository extends CrudRepository<BmsCalendar, Date> {
	@Query("select c from BmsCalendar c where c.year = ?1 and c.bmsMonthofyear.monthofyearId = ?2")
	public List<BmsCalendar> getCalendar(BigDecimal year, BigDecimal month);
	
//	@Query("select c from BmsCalendar c where c.year = ?1 and c.bmsMonthofyear.monthofyearId = ?2")
//	public List<BmsCalendar> getCalendar(BigDecimal year, BigDecimal month);
	
	@Query("select c from BmsCalendar c where c.calendarDate between  ?1 and ?2  ORDER BY c.calendarDate ASC")
	public List<BmsCalendar> getCalendarBetwenDate(Date start, Date end);
	
	@Query("select c from BmsCalendar c where c.dateStr = ?1")
	public Optional<BmsCalendar> getCalendarDateStr(String start);
	
	@Query("select c from BmsCalendar c where c.dateLong = ?1")
	public Optional<BmsCalendar> getCalendarDateLong(BigDecimal start);
	
	@Query("select c from BmsCalendar c where c.dateLong between  ?1 and ?2  ORDER BY c.calendarDate ASC")
	public List<BmsCalendar> getCalendarLong(BigDecimal start, BigDecimal end);
	
	/*
	@Query(value = "from EntityClassTable t where yourDate BETWEEN :startDate AND :endDate")
	public List<EntityClassTable> getAllBetweenDates(@Param("startDate")Date startDate,@Param("endDate")Date endDate);*/
	
}