/*
 * Created on 21 May 2016 ( Time 16:25:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package ht.bms.calendar.domain.repo;


import ht.bms.calendar.domain.BmsDayofweek;
import org.springframework.data.repository.CrudRepository;

import java.math.BigDecimal;






/**
 * Spring JPA Repository for Dayofweek
 * 
 * @author Telosys Tools Generator
 *
 */
public interface DayofweekRepository extends CrudRepository<BmsDayofweek, BigDecimal> {


}