/*
 * Created on 21 May 2016 ( Time 16:25:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package ht.bms.calendar.domain.repo;


import ht.bms.calendar.domain.BmsDayofweek;
import ht.bms.calendar.domain.BmsSetting;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

import java.math.BigDecimal;
import java.util.Optional;


/**
 * Spring JPA Repository for Dayofweek
 * 
 * @author Telosys Tools Generator
 *
 */
public interface SettingRepository extends CrudRepository<BmsSetting, BigDecimal> {

    @Query("select s from BmsSetting s where s.Id = ?1 and s.institutionId = ?2")
    public Optional<BmsSetting> getDefaultSetting(BigDecimal Id, BigDecimal institutionId);

    @Query("select s from BmsSetting s where s.institutionId = ?1")
    public Optional<BmsSetting> findByIsntituion(BigDecimal institutionId);
}